apiVersion: v2
name: userservice
description: A Helm chart for UserService
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - userservice
  - api
  - microservice
home: https://github.com/your-org/monorepo
maintainers:
  - name: Team
    email: team@company.com
