name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DOTNET_VERSION: '9.0.x'
  NODE_VERSION: '18.x'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend-changed: ${{ steps.changes.outputs.frontend }}
      bff-changed: ${{ steps.changes.outputs.bff }}
      userservice-changed: ${{ steps.changes.outputs.userservice }}
      orderservice-changed: ${{ steps.changes.outputs.orderservice }}
      e2e-changed: ${{ steps.changes.outputs.e2e }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            frontend:
              - 'services/Frontend/**'
            bff:
              - 'services/Bff/**'
            userservice:
              - 'services/UserService/**'
            orderservice:
              - 'services/OrderService/**'
            e2e:
              - 'e2e/**'
              - 'global/**'
              - '.github/**'
              - 'tools/**'


  build-and-test-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: services/Frontend/package-lock.json

      - name: Install Angular dependencies
        run: |
          cd services/Frontend
          npm ci

      - name: Build Angular frontend
        run: |
          cd services/Frontend
          npm run build

  build-and-test-bff:
    needs: detect-changes
    if: needs.detect-changes.outputs.bff-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore .NET dependencies
        run: |
          cd services/Bff
          dotnet restore

      - name: Build Bff service
        run: |
          cd services/Bff
          dotnet build --configuration Release --no-restore

      - name: Run Bff unit tests
        run: |
          cd services/Bff
          dotnet test --configuration Release --no-build --verbosity normal

  build-and-test-userservice:
    needs: detect-changes
    if: needs.detect-changes.outputs.userservice-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore .NET dependencies
        run: |
          cd services/UserService
          dotnet restore

      - name: Build UserService
        run: |
          cd services/UserService
          dotnet build --configuration Release --no-restore

      - name: Run UserService unit tests
        run: |
          cd services/UserService
          dotnet test --configuration Release --no-build --verbosity normal

  build-and-test-orderservice:
    needs: detect-changes
    if: needs.detect-changes.outputs.orderservice-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore .NET dependencies
        run: |
          cd services/OrderService
          dotnet restore

      - name: Build OrderService
        run: |
          cd services/OrderService
          dotnet build --configuration Release --no-restore

      - name: Run OrderService unit tests
        run: |
          cd services/OrderService
          dotnet test --configuration Release --no-build --verbosity normal

